name:'THANK YOU ACTION'
description:'Say "Thank you" to new pull request'
author:'Hafiz'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'